### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by adyz** [yyx990803/vue-ssr-demo#2]
I get this after I do `sudo npm install`

    vue-ssr git:(master) node server.js
    /Users/adrian/Desktop/vue-ssr/server.js:68
    let firstChunk = true
        ^^^
    
        SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
    ➜  vue-ssr git:(master)

**Comment by adyz** [comment]
OS: Mac OS X El Capitan
Node Version: v4.4.4

**Comment by yyx990803** [comment]
Fixed now. But preferrably run it with Node 5+

**Comment by adyz** [comment]
Oh darn, thanks for the quick replay.


I think I need a fresh start with my mac environment.


Now I get: 


    ➜  vue-ssr git:(master) ✗ node server.js
    events.js:141
    throw er; // Unhandled 'error' event
    ^
    
    Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventEmitter.listen (/Users/adrian/Desktop/vue-ssr/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/adrian/Desktop/vue-ssr/server.js:51:7)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)

**Comment by yyx990803** [comment]
You have something running on your port 3000 already.

**Comment by adyz** [comment]
Ah, right! 
Thaaanks! 
So excited about the "Holy Grail"
